# Generated by Django 4.2.5 on 2024-03-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIQUE_ID', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='Gadgethub')),
                ('name', models.CharField(max_length=200)),
                ('prize', models.IntegerField()),
                ('Condition', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], max_length=200)),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('INSTOCK', 'INSTOCK'), ('OUTOFSTOCK', 'OUTOFSTOCK')], max_length=200)),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('COMINGSOON', 'COMINGSOON')], max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetapp.categories')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgetapp.filter_price')),
            ],
        ),
    ]
