# Generated by Django 4.2.5 on 2024-03-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
