# Generated by Django 4.2.5 on 2024-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetapp', '0004_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='Contact',
        ),
    ]
