# Generated by Django 4.2.5 on 2024-03-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetapp', '0005_rename_contact_us_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
